export const PERMISSIONS = {
  SUPERADMIN: [
    'UPDATE_PERMISSIONS',

    'CREATE_ADMIN',
    'UPDATE_ADMIN',
    'DELETE_ADMIN',

    'CREATE_PRODUCT',
    'UPDATE_PRODUCT',
    'DELETE_PRODUCT',

    'CREATE_CATEGORY',
    'UPDATE_CATEGORY',
    'DELETE_CATEGORY',

    'VIEW_REPORTS',

    'SEND_NOTIFICATIONS',
  ],
  EMPLOYEE: [
    'CREATE_PRODUCT',
    'UPDATE_PRODUCT',
    'DELETE_PRODUCT',
    'CREATE_CATEGORY',
    'UPDATE_CATEGORY',
    'DELETE_CATEGORY',

    'SEND_NOTIFICATIONS',
  ],
};

export enum ROLES {
  SUPERADMIN = 'SUPERADMIN',
  EMPLOYEE = 'EMPLOYEE',
}

export enum NOTIFICATIONACTIONS {
  SEND_TO_SUBSCRIBED_CATEGORIES = 'SEND_TO_SUBSCRIBED_CATEGORIES',
  SEND_PRODUCT_NOTIFICATION = 'SEND_PRODUCT_NOTIFICATION',
  SEND_FIREBASE_NOTIFICATION = 'SEND_FIREBASE_NOTIFICATION',

  SEND_PRODUCT_NOTIFICATION_TO_SINGLE_USER = 'SEND_PRODUCT_NOTIFICATION_TO_SINGLE_USER',

  CHECK_MY_PRODUCT_PRICE = 'CHECK_MY_PRODUCT_PRICE',

  SEND_TO_SUBSCRIBED_PRODUCTS = 'SEND_TO_SUBSCRIBED_PRODUCTS',
}
