export const PERMISSIONS = {
  SUPERADMIN: [
    'UPDATE_PERMISSIONS',

    'CREATE_ADMIN',
    'UPDATE_ADMIN',
    'DELETE_ADMIN',

    'CREATE_PRODUCT',
    'UPDATE_PRODUCT',
    'DELETE_PRODUCT',

    'CREATE_CATEGORY',
    'UPDATE_CATEGORY',
    'DELETE_CATEGORY',

    'VIEW_REPORTS',

    'SEND_NOTIFICATIONS',
  ],
  EMPLOYEE: [
    'CREATE_PRODUCT',
    'UPDATE_PRODUCT',
    'DELETE_PRODUCT',
    'CREATE_CATEGORY',
    'UPDATE_CATEGORY',
    'DELETE_CATEGORY',

    'SEND_NOTIFICATIONS',
  ],
};

export enum ROLES {
  SUPERADMIN = 'SUPERADMIN',
  EMPLOYEE = 'EMPLOYEE',
}
